
<div id="footer">
	<hr/>
	<div class="footer_menu text-center">
		<ul>
			<li><a href="/"><i class="icon-home"></i>Home</a></li>
			<li><a href="about"><i class="icon-star"></i>About Us</a></li>
			<li><a href="#"><i class="icon-tag"></i>Products</a></li>
			<li><a href="terms"><i class="icon-cog"></i>Terms and Condition</a></li>
			<li><a href="cart"><i class="icon-shopping-cart"></i>My Cart</a></li>
		</ul>
	</div>
	<p class="text-center" id="footer_copyright">&#169 Copyright 2013. WearToInspire.com</p>
	<br/>
</div>
