
<div class="navbar navbar-fixed-top"> <!-- Navigation bar -->
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!-- Logo Brand -->
			<a class="brand" href="/">
				<font color="#bd6cb8">
					<img width="30px" style="display:inlne-block;" src="/img/icon.png" />WeartoInspire
				</font>
			</a>
			<!-- Navigation Buttons -->
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li id="nav_home">
						<a href="/">Home</a>
					</li>
					<li class="dropdown" id="nav_products">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Products<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><a href="products">All Products</a></li>
							<li><a href="products?cat=dresses">Dresses</a></li>
							<li><a href="products?cat=shoes">Shoes</a></li>
							<li><a href="products?cat=bags">Bags</a></li>
							<li><a href="products?cat=accessories">Accessories</a></li>
						</ul>
					</li>
					<li id="nav_about"><a href="about">About</a></li>
					<li><a href="blog">Blog</a></li>
					<li id="nav_terms"><a href="terms">Terms&Conditions</a></li>
					<li  id="nav_cart"><a href="cart">
						<span class="ctm_cart"><img src="/img/cart.png" /><strong> My Cart</strong></span>
						</a>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li>
						<?php
						if(!isset($_SESSION['user'])) {
						echo '
						<a href="login">
						<span class="ctm_fb_login">
						<img src="/img/fb.png" />
						<strong> Login</strong>
						</span>
						</a>';
						}
						else {
						echo '
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<span class="ctm_fb_login">
						<img src="http://graph.facebook.com/'.$_SESSION['user']['user_id'].'/picture" />
						<strong> '.$_SESSION['user']['user_first'].' <b class="caret"></b></strong>
						</span>
						</a>
						<ul class="dropdown-menu">
						<li class="dd"><a href="/logout?q=true"><i class="icon-off"></i> Log-out</a></li>
						</ul>
						';
						}
						?>
					</li>
				</ul>
			</div><!-- End Navigation Buttons -->
		</div>
	</div>
</div>
