<!DOCTYPE html>
<html class="<?php print $class; ?>" lang="en">
	
<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php if(isset($meta) && is_array($meta)): ?>
	<?php foreach($meta as $name => $content): ?>
	<meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
	<?php endforeach; ?>
	<?php endif; ?>
	<link rel="shortcut icon" href="/img/favicon.ico" />
	<link href="css/bootstrap.css" type="text/css" rel="stylesheet" media="screen">
	<link href="css/bootstrap-responsive.css" type="text/css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" media="screen" href="/assets/front/style.css" />
</head>

<body>
	<div class="page">
		<div class="container">
			<div class="head"><?php echo $head; ?></div>
			<div class="body"><?php echo $body; ?></div>
			<div class="foot"><?php echo $foot; ?></div>
		</div>
	</div>
	<script type="text/javascript" src="/assets/front/script.js"></script>
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/bootstrap.min.js"></script>
</body>
</html>
