<br><br><br><br>
<!-- About -->
<div class="container">
	<div class="row">
		<!-- About Heding -->
		<div class="span10 offset1 terms_head text-center">
			<div style="margin-top:10px;color:#777777;">WEAR TO INSPIRE | About Us</div>
		</div>
		<!-- About Body -->
		<div class="span10 offset1 terms">
			<!-- Shop Policy -->
			<div class="span8 offset1">
				<br><br>
				<strong>SHOP POLICY:</strong>
				<br><br>
				<ol>
					<li>We only have 3-day reservation RULE.</li>
					<li>We do not accept meet-ups unless it is in bulk.</li>
					<li>No return, no exchange.</li>
					<li>PLEASE NO "BOGUS BUYER & JOY RESERVERS" if you are one of them your name and picture will post it on my bogus buyer album so beware!</li>
				</ol>
				<br>
			</div>
			<!-- Modes of Payment -->
			<div class="span3 offset1">
				<strong>Modes of Paymment:</strong>
				<br><br>
				<ul>
					<li>M lhuillier</li>
					<li>BDO</li>
					<li>Western union</li>
					<li>BPI</li>
					<li>MONEYGRAM</li>
					<li>XOOM</li>
					<li>GCASH</li>
					<li>Smart Money</li>
				</ul>
				<br>
			</div>
			<!-- Courier -->
			<div class="span2 offset1">
				<strong>Courier:</strong>
				<br><br>
				<ul>
					<li>LBC</li>
					<li>Philfox</li>
					<li>XEND</li>
				</ul>
			</div>
			<!-- Divider -->
			<div class='row span10'>
				<hr class='span3'>
				<span class='span3 text-center'>3 Steps of Buying</span>
				<hr class='span3'>
			</div>
			<!-- 3 Steps -->
			<div class='span8 offset1'>
				<br>
				<ol>
					<li>Choose an item/s you want then ask for its availability. Wait for 24-48hrs for confirmation.</li>
					<li>If you are 101% sure already, please answer an order form to be sent through sms.
						<br><br>
						<ul>
							<li>Full Name:</li>
							<li>Address:</li>
							<li>Contact no.:</li>
							<li>Date of payment:</li>
							<li>Mode of payment:</li>
						</ul>
						<br>
					</li>
					<li>Fully payment </li>
				</ol>
				<br>
				<span class="span8 text-center">** After the payment, the item/s will be shipped instantly.**
					<br>
					FOR FASTER TRANSACTION PM US THRU SMS-- SMART: 09391453047 GLOBE: 09167447437
					<br><br><br>
				</span>
			</div>
		</div><!-- End of Terms Body -->
	</div>
</div><!-- End of terms Container -->
<br><br><br>
<script type="text/javascript">
document.getElementById('nav_about').className='active';
</script>