<br><br><br><br>
<!-- Cart -->
<table class="table table-hover table-bordered table-striped">
	<thead>
		<tr>
			<th class="span1">Item Id</th>
			<th class="span2">Name</th>
			<th class="span2">Price</th>
			<th class="span2">Quantity</th>
			<th class="span2">Subtotal</th>
			<th class="span1">Action</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>DR-701</td>
			<td>P 100.00</td>
			<td><input type="number" class="input-mini" min="1" value="1"></td>
			<td>P 100.00</td>
			<td><button class="btn btn-mini"><i class="icon-picture"></i></button>
				<button class="btn btn-mini"><i class="icon-trash"></i></button></td>
		</tr>
		<tr>
			<td>2</td>
			<td>DR-701</td>
			<td>P 100.00</td>
			<td><input type="number" class="input-mini" min="1" value="1"></td>
			<td>P 100.00</td>
			<td><button class="btn btn-mini"><i class="icon-picture"></i></button>
				<button class="btn btn-mini"><i class="icon-trash"></i></button></td>
		</tr>
		<tr>
			<td>3</td>
			<td>DR-701</td>
			<td>P 100.00</td>
			<td><input type="number" class="input-mini" min="1" value="1"></td>
			<td>P 100.00</td>
			<td><button class="btn btn-mini"><i class="icon-picture"></i></button>
				<button class="btn btn-mini"><i class="icon-trash"></i></button></td>
		</tr>
		<tr>
			<td>4</td>
			<td>DR-701</td>
			<td>P 100.00</td>
			<td><input type="number" class="input-mini" min="1" value="1"></td>
			<td>P 100.00</td>
			<td><button class="btn btn-mini"><i class="icon-picture"></i></button>
				<button class="btn btn-mini"><i class="icon-trash"></i></button></td>
		</tr>
	</tbody>
</table>
<table class="table table-hover table-bordered">
	<thead>
		<tr>
			<th class="span7">Total</th>
			<th class="span3">P 100.00</th>
		</tr>
	</thead>
</table>
<br>
<h3>Order Form:</h3>
<hr>
<div class="row">
<form class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Email">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Contact</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Email">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Location</label>
    <div class="controls">
      <textarea rows="2"></textarea>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Message</label>
    <div class="controls">
      <textarea rows="3"></textarea>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <input type="checkbox"> I agree with the terms and condition
      </label>
      <button class="btn btn-primary btn-large"><i class="icon-arrow-right icon-white"></i> Submit Order</button>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
		<button class="btn disabled btn-info btn-large"><i class="icon-arrow-right icon-white"></i> Checkout</button>
    </div>
  </div>
</form> 
</div>




<br><br><br>
<script type="text/javascript">
document.getElementById('nav_cart').className='active';
</script>