<br><br><br>

<div class="container">
<div class="row">
  <div class="span4">
    <form>
      <fieldset>
        <label>Product ID</label>
        <h3><?php echo (isset($prodDetails['prod_id'])? $prodDetails['prod_id']:''); ?></h3>
        <label>Product name</label>
        <h3><?php echo (isset($prodDetails['prod_name'])? $prodDetails['prod_name']:''); ?></h3>
        <label>Price</label>
        <h3>P <?php echo (isset($prodDetails['prod_price'])? $prodDetails['prod_price']:''); ?>.00</h3>
        <label>Description:</label>
        <p><?php echo (isset($prodDetails['prod_desc'])? $prodDetails['prod_desc']:''); ?></p>
        <br>
        <p><a href="#" class="btn btn-primary"><i class="icon-shopping-cart icon-white"></i>Add to Cart</a></p>
      </fieldset>
    </form>
  </div>
<ul class="thumbnails">
  <li class="span8">
    <div class="thumbnail">
    <img width="100%" src=<?php echo '"'.(isset($prodDetails['prod_image'])? $prodDetails['prod_image']:'').'"'; ?>>
    </div>
  </li>
</ul>
</div>
</div>
<br><br><br>
